config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
  get 'about' => 'pages#about'
  resources :courses do
    member do
      get :delete
    end
  end
  resources :episodes do
    member do
      get :delete
    end
  end
  #get 'courses' => 'courses#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
     
     has_many :episodes #, class_name: "episode", foreign_key: "reference_id", dependent: :destroy
    mount_uploader :image, ImageUploader

    validate :image_size


    private
        # Validates the size of an uploaded image
        def image_size
            if image.size > 5.megabytes
                errors.add(:image, 'Should be less than 5MB')
            end
        end
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
    
  end

  def show
    @course = Course.find(params[:id]) 

    # if @courset.nil 
    #   redirect_to root_path
    # end
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = 'You created a new course'
      redirect_to @course
    else
      render 'new'
    end 
  end

  def edit 
    @course = Course.find(params[:id])
  end

  def update 
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  def delete 
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id]).destroy 
    flash[:success] = 'Course removed successfully!'
    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :image)
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  # before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /episodes
  def index
    @episodes = Episode.all
    # @episodes = Episode.find_by(course_id: @course)
  end

  # GET /episodes/1
  def show
    @episode = Episode.find(params[:id])
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
  end

  # POST /episodes
  def create
    @episode = Episode.new(episode_params)
      if @episode.save
        redirect_to @episode, notice: "Episode was successfully created." 
      else
        render :new
      end
  end
  def update
    @episode = Episode.find(params[:id])
    if @episode.update(episode_params)
      redirect_to @episode, notice: "Episode was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /episodes/1
  def destroy
    @episode.destroy
      redirect_to episodes_url, notice: "Episode was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_episode
    #   @episode = Episode.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:course_id, :title, :description, :order, :video_link)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
    # load_courses
    @courses = Course.all
  end

  def about
  end

  # private

  # def load_courses
  #   @courses = Course.all
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

    #Returns the full title on, per page basis
		def full_title(page_title ='')
      base_title = "Online Courses"
        if page_title.empty?
          base_title
        else
          "#{page_title} | #{base_title}"
        end
    end

    def image_for(course, options= { size: 100})
      size = options[:size]
      if course.image?
          image_tag course.image.url(:thumb), width: size, class: "card-img-top"
      end
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/_form.html.erb
    
    <%= f.label :title %>
    <%= f.text_field :title%>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :image %>
    <%= f.file_field :image%>

app/views/courses/delete.html.erb
<div class="container">
<div class="delete">
    <h1>Delete Course</h1>
    <br>
    <%= form_for(@course, method: "delete") do |f| %>

    <p class="alert alert-danger" role="alert" >Are you sure you want permenantly delete this course?</p>
    <p><strong><%= @course.title %></strong></p>
    <br>
    <div class="form-buttons"><%= f.submit "Delete Course", class: "btn btn-primary" %></div>

    <% end %>
</div>
<%= link_to "<< Back to list", courses_path, class: 'badge badge-primary Back-link' %>
</div>

app/views/courses/edit.html.erb
<% provide(title: "Edit Course") %>
<div class="container">
    <h1>Update Course</h1>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <%= form_for(@course) do |f|%>

            <%= render :partial => 'form', :locals =>{:f => f}  %>

            <div class="form-buttons">
                <%= f.submit "Save changes", class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/courses/index.html.erb
<div class="container index">
<h1>Courses</h1>
    
    <table class="listing table" summary='Course list'>
        <thead>
            <tr class='header'>
                <th scope="col">Title</th>
                <th scope="col">Image</th>
                <th scope="col">Description</th>
                <th scope="col"></th>
            </tr>
        </thead>

        <% @courses.each do |course| %>

            <tr>
                <td><%= course.title %></td>
                <td><%= image_for(course) %></td>
                <td><%= course.description %></td>
                <td class="actions">
                    <%= link_to "Show", course_path(course) %>
                    <%= link_to "Edit", edit_course_path(course) %>
                    <%= link_to "Delete", delete_course_path(course) %>
                </td>
            </tr>
        <% end %>
    </table>
</div>
<p><%= link_to "Add New Course", new_course_path, class: 'badge badge-primary action new' %></p>

app/views/courses/new.html.erb
<% provide(:title, "New Course") %>
<h1>Create New Course</h1>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <%= form_for (@course), html: { multipart: true } do |f| %>
            <%= render :partial => 'form', :locals =>{:f => f}  %>
            <%= f.submit "Create Course", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/courses/show.html.erb
<div class="container">

    <div class="course show">
        <h1><%= @course.title %></h1>
        <br>   
        <p><%= @course.description %></p>
        <br>
        <section> 
            <h2>Course content</h2>
            <ol>
            <% @course.episodes.each do |episode| %>
                <li><h3><%= episode.title %></h3></li>
                <p><%= episode.description %></p>
            <% end %>
            </ol>
        </section>
    </div>
    <%= link_to "Back", courses_path %>
</div>

app/views/episodes/_form.html.erb
<%= f.label :course %>
<%= f.text_field :course_id %>
<%= f.label :title %>
<%= f.text_field :title%>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :order %>
<%= f.number_field :order%>
<%= f.label :video_link %>
<%= f.text_field :video_link%>

app/views/episodes/edit.html.erb
<% provide(title: "Edit Episode") %>
<div class="container">
    <h1>Update Episode</h1>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <%= form_for(@episode) do |f| %>
            <%= render partial: 'form',  :locals =>{:f => f}  %>
            <div class="form-buttons">
                <%= f.submit "Save changes", class: "btn btn-primary" %>
            </div>
            <div>
                <%= link_to 'Show', @episode %> |
                <%= link_to 'Back', episodes_path %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/episodes/index.html.erb
<%# <p id="notice"><%= notice %>

<div class="container index">
<h1>Episodes</h1>
    
<table class="listing table" summary='Episodes list'>
  <thead>
    <tr class='header'>
      <th scope="col">Course</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Order</th>
      <th scope="col">Video Link</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.course.title if episode.course %></td>
        <td><%= episode.title %></td>
        <td><%= episode.description %></td>
        <td><%= episode.order %></td>
        <td><%= episode.video_link %></td>
        <td class="action">
          <%= link_to 'Show', episode_path(episode) %>
          <%= link_to 'Edit', edit_episode_path(episode) %>
          <%= link_to 'Destroy', delete_episode_path(episode) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path, class: 'badge badge-primary action new' %>

app/views/episodes/new.html.erb
<% provide(:title, "New Episode") %>
<h1>New Episode</h1>
<p><%= link_to 'Back', episodes_path %></p>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <%= form_for @episode, html: { multipart: true } do |f| %>
            <%= render partial: 'form', locals: {f: f}  %> 
            <%= f.submit "Create Episode", class: "btn btn-primary" %>
        <% end %>
    </div>
    
</div>

app/views/episodes/show.html.erb
<%# <p id="notice"><%= notice %>
<div class="container">
    <div class="episode show">

        <h1><%= @episode.course.title  %></h1>
        <br>   
        <p><%= @episode.course.description %></p>
        <br> 
        <section> 
            <h2>Course content</h2>
            
                <%# <% @episodes.each do |e| %>  
                    <%# <% if e.course_id == course_id %>  
                        <%# <h3><%= e.id %>
                        <%# <%= e.title %>
                        <%# <p><%= e.description %>
                    <%# <% end %> 
                <%# <% end %>
        </section>
    </div>
</div>
<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/_footer.html.erb
<footer class=" footer">
    <div class="row">
        <div class="col first">
            <%= link_to "Business", "#", class: "nav-link active" %>
            <%= link_to "Teach on Here", "#", class: "nav-link active" %>
            <%= link_to "Get the app", "#", class: "nav-link active" %>
        </div>
        <div class="col careers">
            <%= link_to "Careers", "#", class: "nav-link" %>
            <%= link_to "Blog", "#", class: "nav-link" %>
            <%= link_to "Help and Support", "#", class: "nav-link" %>
            <%= link_to "Affiliate", "#", class: "nav-link" %>
        </div>
        <div class="col terms">
            <%= link_to "Terms", "#", class: "nav-link active" %>
            <%= link_to "Privacy policy", "#", class: "nav-link active" %>
            <%= link_to "Sitemap", "#", class: "nav-link active" %>
            <%= link_to "Featured courses", "#", class: "nav-link active" %>
            <%= link_to "Cookie settings", "#", class: "nav-link active" %>
        </div>
        <div class="col about">
            <%= link_to "About us", "#", class: "nav-link active" %>
            <%= link_to "Contact us", "#", class: "nav-link active" %>
        </div>
    </div>
    <div class="row">
        <div class="col copy">
            <small>
                <p class="pb-3 center">The <%= link_to "Online Course", "#" %> By Clode U - &copy; 2021 All rights reserved.<p>
            </small>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
    <div class="container">
        <%= link_to "ONLINE COURSE", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><%= link_to "Courses", root_path, class: "nav-link" %>
                <span class="sr-only">(current)</span></li>
                <li class="nav-item"><%= link_to "About", about_path, class: "nav-link"%></li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2 mb-0" type="search" placeholder="Search for anything" aria-label="Search">
                <button class="btn btn-outline-success my-0 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="main-container"> 
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <%= yield %>
      
    <%= render 'layouts/footer' %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About us") %>
<h1>About Us</h1>
<p>This is the best online courses App ever existed</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a sem sed ipsum hendrerit blandit hendrerit at velit. Nullam congue enim eget nisl vestibulum scelerisque. Phasellus pharetra neque vitae finibus eleifend. Aenean id enim varius, scelerisque ipsum id, condimentum nibh. Proin sit amet volutpat orci. Sed leo leo, viverra at mollis ac, venenatis sed magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

app/views/pages/index.html.erb
<div class="jumbotron jumbotron-fluid bg-info text-white">
  <h1 class="display-4">Welcome to our online courses platform </h1>
  <p class=" center lead">Learn the latest skills to reach your professional goals!</p>
  <div class="container">
    <hr class="my-4">
    <div class="card text-info" style="width: 24rem;">
      <div class="card-body">
        <h5 class="card-title">Dream up</h5>
        <p class="card-text">Ambition accepted. Learn the latest skills to reach your professional goals.
        You will find Top instructors from around the world teach millions of students on our app. 
        We provide the tools and skills to teach you what you love.</p>
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="What do you want to learn?" aria-label="What do you want to learn" aria-describedby="button-addon2">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2">Button</button>
          </div>
        </div>
      </div>
    </div>
    <div class="card float-right">
      <div class="text-hide" style="background-image: url('https://unsplash.com/photos/bzqjws3MZAc');">
      Image of a girl in red dress
      </div>
    </div>
  </div>
</div>
<article class="container">
  <h2 class="mb-2">The world's largest selection of courses</h2>
  <p class="center mb-5">Choose from 130,000 online video courses with new additions published every month</p>
</article>

<section class="courses my-5 py-4">
  <% @courses.in_groups_of(6,false).each do |group| %>
  <div class="row row-cols-1 row-cols-md-6" >
    <% group.each do |course| %>
      <div class="col mb-4">
        <div class="card border-0 course-card">
          <%= image_for(course) %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to course.title, course_path(course) %></h5>
            <p class="card-text"><%= course.description.truncate(70) %></p>
          </div> 
        </div>
      </div>
      <% end %>    
  </div>
<% end %> 
</section>

    <section class="my-5">
      <div class="jumbotron jumbotron-fluid text-center recommendations text-light">
        <h2 class="text-light">Get personal learning recommendations</h1>
        <p class="lead">Answer few questions for your top picks </p>
        <a class="btn btn-outline-light btn-lg" href="#" role="button">Get started</a>
      </div>
    </section>

<section class="my-5">
  <%# <div class="container"> %>
    <h2>Featured topics by category </h2>
      <h3 class="center">(<%=@courses.count%>) Courses available</h3>
        <% @courses.in_groups_of(6,false).each do |group| %>
          <dl class="" >
            <div class="m-3 d-flex flex-row" >
              <% group.each do |c| %>
                <div class="m-2" id="course">
                  <h4><%= c.title if c.title %></h4>
                    <% c.episodes.each do |e|%>
                      <dd Class="p-2 flex-fill"> <%= e.title %></dd>
                    <% end %>
                </div>
              <% end %>
            </div>
          </dl>
        <% end %> 
        <a class="btn btn-info btn-lg m-3" href="#" role="button">Explore more</a>
  <%# </div> %>
</section>
    <section class="my-5">
      <div class="jumbotron instructors">
        <div class="row row-cols-1 row-cols-md-2">
        <div class="col mb-2">
        <div class="card bg-dark text-white">
          <img src="..." class="card-img" alt="...">
          <div class="card-img-overlay">
            <h2 class="card-title">Image goes here</h2>
          </div>
          </div>
        </div>
        <div class="col mb-2">
        <div class="card bg-transparent border-0 ml-5">
          <div class="card-body">
            <h2 class="card-title text-left">Become an instructor</h2>
            <p class="card-text">Top instructors from around the world teach millions of students on Here. We provide the tools and skills to teach what you love.</p>
            <a href="#" class="btn btn-info">Start searching today</a>
          </div>
        </div>
      </div>
    </section>
    <section class="my-5">
      <h2>Your testimonies</h2>
      <div class="row row-cols-1 row-cols-md-3">
        <div class="col mb-4">
          <div class="card border-0">
            <div class="card-body text-center">
              <img class="avatar rounded-circle" src="..." alt="Image">
              <h5 class="card-title">Robert Downey Jr.</h5>
              <h6 class="card-subtitle mb-2 text-muted">Famous Actor</h6>
              <p class="card-text">"Robert John Downey Jr.'career has included critical and popular success in his youth, followed by a period of substance abuse and legal difficulties, and a resurgence of commercial success in middle age."</p>
              <a href="#" class="btn btn-info">Follow</a>
              <a href="#" class="btn btn-outline-info">Message</a>
            </div>
          </div>
        </div>
        <div class="col mb-4">
          <div class="card border-0">
            <div class="card-body text-center">
              <img class="avatar rounded-circle" src="..." alt="Image">
              <h5 class="card-title">Robert Downey Jr.</h5>
              <h6 class="card-subtitle mb-2 text-muted">Famous Actor</h6>
              <p class="card-text">"Robert John Downey Jr.'career has included critical and popular success in his youth, followed by a period of substance abuse and legal difficulties, and a resurgence of commercial success in middle age."</p>
              <a href="#" class="btn btn-info">Follow</a>
              <a href="#" class="btn btn-outline-info">Message</a>
            </div> 
          </div>
        </div>
        <div class="col mb-4">
          <div class="card border-0">
            <div class="card-body text-center">
              <img class="avatar rounded-circle" src="..." alt="Image">
              <h5 class="card-title">Robert Downey Jr.</h5>
              <h6 class="card-subtitle mb-2 text-muted">Famous Actor</h6>
              <p class="card-text">"Robert John Downey Jr.'career has included critical and popular success in his youth, followed by a period of substance abuse and legal difficulties, and a resurgence of commercial success in middle age."</p>
              <a href="#" class="btn btn-info">Follow</a>
              <a href="#" class="btn btn-outline-info">Message</a>
            </div>
          </div>
        </div>
        </div>
      </div>
    </section>

    <section class="my-5">
    <div class="jumbotron jumbotron-fluid border-top border-dark bg-transparent">
    <div class="row row-cols-1 row-cols-md-2">
      <div class="col mb-2">
        <div class="card bg-transparent border-0">
        <img src="..." class="card-img" alt="...">
          <div class="card-img-overlay">
            <h2 class="card-title text-left">Video goes here</h2>
          </div>
        </div>
        </div>
        <div class="col mb-2">
        <div class="card border-0">
          
          <div class="card-body">
            <h2 class="card-title">Transform your life through education</h2>
            <p class="card-text">Modimba Kamalaloush launched a new career in software development by taking courses on Here. What will you be able to do?</p>
          </div>
          </div>
        </div>
      </div>
    </div>
    </section>